
services:
  travel-service:
    container_name: travel_backend
    build:
      context: .
      dockerfile: ./Dockerfile-local
    ports:
      - 9000:9000
      - 5678:5678
    restart: always
    environment:
    - SQLALCHEMY_DATABASE_URI=postgresql+asyncpg://scott:tiger@travel_postgres_db:5432/travel_service_db
    command: uvicorn app.app_definition:travel_agency_api --host=0.0.0.0 --port 9000 --reload
    volumes:
      - ./src:/src
    depends_on:
    - travel-db


  travel-db:
    container_name: travel_postgres_db
    image: postgres:14
    volumes:
      - travel_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: travel_service_db

    ports:
      - 5432:5432
    restart: always 
      
volumes:
  travel_postgres_data:



