"""table creation

Revision ID: 194ff8b32030
Revises: 
Create Date: 2026-04-11 11:03:55.723011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194ff8b32030'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(length=25), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempted_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='travel_schema'
    )
    op.create_table('user_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('alternative_mobile_number', sa.String(length=25), nullable=True),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username'),
    schema='travel_schema'
    )
    op.create_table('device_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.String(length=254), nullable=True),
    sa.Column('device_token', sa.String(length=1000), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='travel_schema'
    )
    op.create_table('driver_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id'),
    schema='travel_schema'
    )
    op.create_table('passenger_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='travel_schema'
    )
    op.create_table('refresh_tokens_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['travel_schema.device_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti'),
    schema='travel_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens_table', schema='travel_schema')
    op.drop_table('passenger_table', schema='travel_schema')
    op.drop_table('driver_table', schema='travel_schema')
    op.drop_table('device_table', schema='travel_schema')
    op.drop_table('user_table', schema='travel_schema')
    op.drop_table('otp_table', schema='travel_schema')
    # ### end Alembic commands ###
