"""first time user column

Revision ID: 21f91c987dc5
Revises: 5e2ff4f76e2e
Create Date: 2026-04-23 14:08:49.943817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f91c987dc5'
down_revision: Union[str, Sequence[str], None] = '5e2ff4f76e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_table', sa.Column('is_first_time_only', sa.Boolean(), nullable=True), schema='travel_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon_table', 'is_first_time_only', schema='travel_schema')
    # ### end Alembic commands ###
