"""trip table and vehicle table created

Revision ID: 40430bf25ff2
Revises: 194ff8b32030
Create Date: 2026-04-18 13:04:23.952900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40430bf25ff2'
down_revision: Union[str, Sequence[str], None] = '194ff8b32030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('no_of_seats', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number'),
    schema='travel_schema'
    )
    op.create_table('trip_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('starting_time', sa.DateTime(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['travel_schema.driver_table.id'], ),
    sa.ForeignKeyConstraint(['vehicle_number'], ['travel_schema.vehicle_table.vehicle_number'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='travel_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_table', schema='travel_schema')
    op.drop_table('vehicle_table', schema='travel_schema')
    # ### end Alembic commands ###
