"""create wallet table

Revision ID: 53d9f37ad461
Revises: 7eedb6211b61
Create Date: 2026-04-28 11:38:55.000875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d9f37ad461'
down_revision: Union[str, Sequence[str], None] = '7eedb6211b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='travel_schema'
    )
    op.add_column('user_table', sa.Column('referral_code', sa.String(length=20), nullable=True), schema='travel_schema')
    op.add_column('user_table', sa.Column('referred_by', sa.String(length=20), nullable=True), schema='travel_schema')
    op.create_unique_constraint(None, 'user_table', ['referral_code'], schema='travel_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', schema='travel_schema', type_='unique')
    op.drop_column('user_table', 'referred_by', schema='travel_schema')
    op.drop_column('user_table', 'referral_code', schema='travel_schema')
    op.drop_table('wallet_table', schema='travel_schema')
    # ### end Alembic commands ###
