"""coupon_code

Revision ID: 5e2ff4f76e2e
Revises: fd0d8294711c
Create Date: 2026-04-22 13:03:36.740323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2ff4f76e2e'
down_revision: Union[str, Sequence[str], None] = 'fd0d8294711c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='travel_schema'
    )
    op.add_column('booking_table', sa.Column('transaction_id', sa.String(length=255), nullable=True), schema='travel_schema')
    op.add_column(
    'booking_table',
    sa.Column(
        'coupon_applied',
        sa.Boolean(),
        nullable=False,
        server_default='false'  
    ),
    schema='travel_schema'
)
    op.add_column('booking_table', sa.Column('coupon_code', sa.String(length=100), nullable=True), schema='travel_schema')
    op.add_column('booking_table', sa.Column('discount_amount', sa.Float(), nullable=True), schema='travel_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_table', 'discount_amount', schema='travel_schema')
    op.drop_column('booking_table', 'coupon_code', schema='travel_schema')
    op.drop_column('booking_table', 'coupon_applied', schema='travel_schema')
    op.drop_column('booking_table', 'transaction_id', schema='travel_schema')
    op.drop_table('coupon_table', schema='travel_schema')
    # ### end Alembic commands ###
