"""add coupon_type

Revision ID: 7eedb6211b61
Revises: 21f91c987dc5
Create Date: 2026-04-28 09:59:38.849704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eedb6211b61'
down_revision: Union[str, Sequence[str], None] = '21f91c987dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_table', sa.Column('coupon_type', sa.String(), nullable=True), schema='travel_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon_table', 'coupon_type', schema='travel_schema')
    # ### end Alembic commands ###
