"""booking_table

Revision ID: fd0d8294711c
Revises: 40430bf25ff2
Create Date: 2026-04-22 10:02:30.890461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0d8294711c'
down_revision: Union[str, Sequence[str], None] = '40430bf25ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['travel_schema.trip_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['travel_schema.user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='travel_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table', schema='travel_schema')
    # ### end Alembic commands ###
